name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use nightly Rust compiler
      run: rustup default nightly
    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: Install grcov
      run: cargo install grcov
    - name: Configure cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: wedis-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: "-Cinstrument-coverage"
    - name: Run tests
      run: cargo test --verbose
      env:
        LLVM_PROFILE_FILE: "wedis-%p-%m.profraw"
        RUSTFLAGS: "-Cinstrument-coverage"
    - name: Generate coverage reports
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
